language: generic
before_install:
- sudo apt-get install texlive-binaries
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
  channels conda-forge; conda config --set always_yes yes; conda install tectonic==0.1.12;
  fi
- conda install -c malramsay biber==2.12 --yes
- conda info -a
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/.cache/Tectonic"
script:
- cd ./
- tectonic --keep-intermediates --reruns 0 ./sample-sigconf.tex
- if [ -f "sample-sigconf.bcf" ]; then biber sample-sigconf; fi
- tectonic ./sample-sigconf.tex --print
deploy:
  provider: releases
  skip_cleanup: true
  file: "./sample-sigconf.pdf"
  on:
    branch: master
env:
  global:
  - secure: n2UHipnKJU3TLWhZU1JHvc7IdNP4lUx37duHKuNtHVy+cfHae1RyEm5HPIVB11jw7mWlWKY/HIQeoCD/NPfWtP82FIDt7nGr4jmgS0rz0fh/O0cgWyNRqoJUjtJhMwviKYikLCet2b7Dx/JlujhvFgalUSuTEpLK+qdoZJgIyr7y5VZGlxzn+KiVHZ8pD0hlJDn/BzQtMosOXVThqM5Vki3wb1qWZwpGfduB/Td4d1rdM8ifrOQ0b6udPqfIeswx5k/gg4Tczvgu9406I9hc5sGsAgFjEYtkxoSTOKKhpDrxptnpzAWEuPSAsccEwX9mFh/lfwwddn3bWf8p2W84JxBQEbChT0Ep7D8nxGPDE089ptxAk3bDoczQcMFqeVC2jy1JKIRGecsRs7nVIyJO7VLNZ3edLxHcKD/MAPnqJUuhhtFpUjFfdESjYD879qg+4Vj+hJH/TzHYMVT/OREWvGhi8MRX9TZXqwjiLTGvhnfsnZgtMG6iXHlPG6d39JS2dkD/XwU5yFEan3QyeUIKPOyZ9H5nm6yLjEty2qfFLYw/EcLnHbzPo4J5T90y3W6kPTaBBFBR2yCihtBIr3uiIS2g24uFejwWsnSy/vDVLmTABNH8R2lVxe2EWrDVzRSUHlltRHeOk1z8fZNMo+agjOSps3i/usTM5rFBMBkwe3Y=
