language: generic
before_install:
- sudo apt-get install texlive-binaries
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
  channels conda-forge; conda config --set always_yes yes; conda install tectonic==0.1.12;
  fi
- conda install -c malramsay biber==2.12 --yes
- conda info -a
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/.cache/Tectonic"
script:
- cd ./
- tectonic --keep-intermediates --reruns 0 ./sample-sigconf.tex
- if [ -f "sample-sigconf.bcf" ]; then biber sample-sigconf; fi
- tectonic ./sample-sigconf.tex --print
deploy:
  provider: releases
  skip_cleanup: true
  file: "./sample-sigconf.pdf"
  on:
    branch: master
env:
  global:
    secure: dXfr0wI8VTRVZQ18nX8/ztoBAhY864w3/sfFAlbjVSTVTH+1+ym1020BTUFhQxdncHry+NuUVJPa4OpkXY/Hvvm8Y1n5S3hbvRUrxXp3N9oQS7i+oSqco9GmNqIWUagn7j4GCYnutmnyx3axbRCortF1ac8/rOMpnlWx9OevisLRHNR8ZRlT39C0fMgnRwBEklRqtU6yJ9ziPqtf7hNNkpvaEQ7Ma7QW5JuqbhPBaN8d++IV9VM+cAr8q23cU7v8uFHo8E8f3LuEHQsqtSuCZAZ1fWDhjM9h8BtKMthy2rwTvp6J1A+yjIUeJapXclvh9gMmpvfbj5zMuBPY6XEaysXAbik4C3dj6e1gIFjJ62tp15sh6nswzBeJEhnzfTJ76j5cvQlF4UcC4Y6sE0FTF4TWeXBF7c06e3mAZhzAjp0GZAe9mWQC/FGdkTJb7Sa8bHBNtrbu+ES3qiVYGka2GIamkke1XU0qbxrhUxTnK41yUU5oDemSQSC/nNp2wV+jMAeifiewA8dCHJR/OrWCCkBLGUjWzpcM6kiPhwLwcg5BAJ1H4LubE3+p5HY/xs5m9dO2FNAdxUdetnUZXP0lNu7Pzi05Urj4AaXgAohMnK7cdBfKLVxuS0rgkhUKm7Xw3NS47xZ71IMbhmXIzK3SxBEPEWW9G8NNS9lBiW1RMno=
