language: generic

before_install:
  # Install makeindex, if you do not use an index you can remove this (also remove the extra makeindex call).
  - sudo apt-get install texlive-binaries

install:
  # Silent install from conda docs
  # https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
  # adapted using
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda
  # and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.12;
    fi
  # Install biber if required for compiling the references.
  # Biber version should match the biblatex version of Tectonic
  - conda install -c malramsay biber==2.12 --yes
  - conda info -a
  # Workaround if a specific bundle is needed
#  - sudo mkdir -p ~/.config/Tectonic/
#  - echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
#  - sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\"" | sudo tee --append ~/.config/Tectonic/config.toml
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic
script: # Change working directory each time so including files will work. Change back so the pdfs can be found for deployment. This way, building multiple files goes well.
 - cd ./
 # Run tectonic once to generate intermediate files
 - tectonic --keep-intermediates --reruns 0 ./sample-sigconf.tex
 # If a bcf file exists run biber to compile references
 - if [ -f "sample-sigconf.bcf" ]; then biber sample-sigconf; fi

 # Final run of tectonic to create output
 - tectonic ./sample-sigconf.tex --print
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aLghbis4oXdI2LLFmo22igGRMKn10IurCgf+SK4vgoMRpMjaaxlKuT6FGSppoLSqOu1UmIokTbEqAcmEPpBn8L7y2jVwhV28ofiLTuSrQGn0KRwmFqNtPeZVxzHtLMqKu4LvLdpQnm7+gAlzJeP5vvsohQfmylqSQRtCukRu7VgphGBH2MkNku+uBZt4d+eT3KMR+SOaMJBmCG9rT9m7dR1AkqYsV73M8ahoUEB/brlrJjtgLjOG95Hr4Qiu3Vqs31FlmHyc/sKazsfYMR2wP0038R54h/cS4ZgIzJ8Vai4pN6ZvnyQmHtgoTbTL3WDeWP3YgUVrfNPCzsxZmGrukyziNtbxIl/yMgyQhXrjX+mT12xWH+L8H8VxNJSd4cs8RN4pPSaFztiS0YCorViYlh2UnP2Hz1/DcXmEXa+BjGN1I60gQ+LktrULpEjX4GwIMMF0IpWRs7Jt9H1DFrC2s8Ggd5B2TbAd+Ug8yhdvJIChIdAQmp1/rcNico1f7wUDPC44uYmQKEMAQ3G+nDR2VXBaII/ScCduz1vEc9Rg51dZnEw0KuUe217P9aI8iIV+eg4uw48tEadmDEwwYqmXB7gD84kRE1W/HLnc3jdlB7zfjhcHDi2vx+icPVu1wqY/0CeBdYpN4lbTLMdv/Fw9UiLUDKbsUml4uRzuO2nhqA0=
  file: ./sample-sigconf.pdf
  on:
    branch: master